### ISSUE TITLE
java.lang.NoClassDefFoundError: net/minecraft/world/World$2 Crash

### ISSUE THREAD

**Issue by RavenholmZombie** [SleepyTrousers/EnderIO#5409]
#### Issue Description:

After upgrading Ender IO from 0.5.76 to 5.2.99, the game crashes with a NoClassDefFoundError when loading up a world.

#### What happens:

The game crashes when loading a world with Ender IO blocks from the older version in it.

#### What you expected to happen:

The world to load up normally.

#### Steps to reproduce:

1. Install Ender IO 5.2.99
2. Launch Minecraft
3. Attempt to load into a world with blocks from the previous version of Ender IO.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.2.99
- EnderCore: 0.5.76
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? Single Player

#### Your most recent log file where the issue was present: 

[https://pastebin.com/d2gwtkC3]

**Comment by HenryLoenwind** [comment]
This is cause be either Optifine or Forge doing something that prevents the `World` class from being loaded completely. Nothing to do with us and nothing we can do about, sorry.

**Comment by HenryLoenwind** [comment]
PS: I added code to try to load that class during startup. No idea if this would help in any way, but you may want to try the development version here: https://ci.tterrag.com/job/EnderIO-Modules/job/EnderIO-Hourly/1212/ (in about an hour).
